export const routes = {
    home: '/',
    signIn: '/sign-in',
    signUp: '/sign-up',
    post: '/post',
    popularPosts: '/popular-posts',
    searchPosts: '/search-posts',
    profile: '/profile',
    chat: '/chat',
    categoryAll: '/post?category=all',
    categoryArticle: '/post?category=article',
    categoryHarbit: '/post?category=harbit',
    categoryIt: '/post?category=it',
    categoryJobs: '/post?category=jobs',
    categoryCook: '/post?category=cook',
    categotryInterior: '/post?category=interior',
    categoryFashion: '/post?category=fashion',
    categoryFitness: '/post?category=article&detailCategory=fitness',
    categoryMusic: '/post?category=article&detailCategory=music',
    categoryDance: '/post?category=article&detailCategory=dance',
    categoryDesign: '/post?category=it&detailCategory=design',
    categoryDevelopment: '/post?category=it&detailCategory=development',
    categoryMarketing: '/post?category=it&detailCategory=marketing',
    categoryVideoProduction:
        '/post?category=it&detailCategory=video-production',
    categoryJobInterview: '/post?category=jobs&detailCategory=job-interview',
    categoryPortfolioResumeReview:
        '/post?category=jobs&detailCategory=portfolio-resume-review',
    categoryKoreanCuisine: '/post?category=cook&detailCategory=korean',
    categoryWesternCuisine: '/post?category=cook&detailCategory=western',
    categoryChineseCuisine: '/post?category=cook&detailCategory=chinese',
    categoryJapaneseCuisine: '/post?category=cook&detailCategory=japanese',
    categoryBakery: '/post?category=cook&detailCategory=bakery',
    categoryCody: '/post?category=fashion&detailCategory=cody',
    categoryMakeup: '/post?category=fashion&detailCategory=makeup',
    categoryHair: '/post?category=fashion&detailCategory=hair',
};
