import type { ChatType } from './types';

export const CHAT_MOCK_DATA_1: ChatType[] = [
    {
        chatId: 'chat-1',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '안녕하세요! 아이돌 취업 관련해서 몇 가지 질문드려도 될까요?',
        sentAt: '2025-06-23T12:00:01Z',
        read: true,
    },
    {
        chatId: 'chat-2',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content: '네, 안녕하세요! 물론이죠. 어떤 게 궁금하세요?',
        sentAt: '2025-06-23T12:00:30Z',
        read: true,
    },
    {
        chatId: 'chat-3',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '우선, 기획사 오디션은 보통 어떤 것들을 중점적으로 보나요?',
        sentAt: '2025-06-23T12:01:05Z',
        read: true,
    },
    {
        chatId: 'chat-4',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '주로 춤, 노래, 랩 실력을 기본으로 보고, 비주얼과 스타성도 중요하게 봐요. 자신만의 매력을 어필하는 게 중요해요.',
        sentAt: '2025-06-23T12:01:45Z',
        read: true,
    },
    {
        chatId: 'chat-5',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '그렇군요. 보컬 트레이닝은 어떤 식으로 받는 게 효과적일까요?',
        sentAt: '2025-06-23T12:02:10Z',
        read: true,
    },
    {
        chatId: 'chat-6',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '전문 보컬 학원을 다니는 게 가장 좋고, 매일 꾸준히 발성 연습을 하는 게 중요해요. 녹음해서 들어보는 습관도 큰 도움이 돼요.',
        sentAt: '2025-06-23T12:02:55Z',
        read: true,
    },
    {
        chatId: 'chat-7',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '춤은 원래 못 추는데, 지금부터 배워도 가능성이 있을까요?',
        sentAt: '2025-06-23T12:03:20Z',
        read: true,
    },
    {
        chatId: 'chat-8',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '그럼요! 재능도 중요하지만 노력이 더 중요해요. 기본기부터 차근차근 배우고, 영상을 많이 보면서 따라춰보는 걸 추천해요.',
        sentAt: '2025-06-23T12:04:00Z',
        read: true,
    },
    {
        chatId: 'chat-9',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '답변 감사합니다! 혹시 연습생 생활은 어떤가요? 많이 힘든가요?',
        sentAt: '2025-06-23T12:04:35Z',
        read: true,
    },
    {
        chatId: 'chat-10',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '솔직히 쉽지는 않아요. 매일 반복되는 연습과 월말 평가에 대한 압박감이 크죠. 그래도 꿈을 향해 달려가는 동료들이 있어서 힘이 돼요.',
        sentAt: '2025-06-23T12:05:20Z',
        read: true,
    },
    {
        chatId: 'chat-11',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '식단 관리나 체중 관리는 어떻게 하시나요?',
        sentAt: '2025-06-23T12:05:45Z',
        read: true,
    },
    {
        chatId: 'chat-12',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '회사에서 정해준 식단이 있긴 한데, 기본적으로는 고단백 저탄수화물 위주로 먹고 꾸준히 운동해요. 샐러드를 자주 먹게 되더라고요.',
        sentAt: '2025-06-23T12:06:30Z',
        read: true,
    },
    {
        chatId: 'chat-13',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '오디션 볼 때 팁 같은 게 있을까요? 너무 떨릴 것 같아요.',
        sentAt: '2025-06-23T12:07:00Z',
        read: true,
    },
    {
        chatId: 'chat-14',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '자신감 있는 태도가 제일 중요해요! 심사위원들 눈을 마주치고, 준비한 걸 후회 없이 다 보여주겠다는 생각으로 임하면 좋은 결과가 있을 거예요.',
        sentAt: '2025-06-23T12:07:50Z',
        read: true,
    },
    {
        chatId: 'chat-15',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '자유 연기나 개인기는 어떤 걸 준비하는 게 좋을까요?',
        sentAt: '2025-06-23T12:08:20Z',
        read: true,
    },
    {
        chatId: 'chat-16',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '자신의 매력을 가장 잘 보여줄 수 있는 걸로 준비해야죠. 남들이 다 하는 것보다는 신선하고 독창적인 게 좋아요. 모창이나 악기 연주 같은 것도 좋고요.',
        sentAt: '2025-06-23T12:09:10Z',
        read: true,
    },
    {
        chatId: 'chat-17',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '연습생 계약 기간은 보통 어느 정도 되나요?',
        sentAt: '2025-06-23T12:09:40Z',
        read: true,
    },
    {
        chatId: 'chat-18',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '회사마다 다르지만 보통 2~3년 단위로 계약하는 것 같아요. 그 안에 데뷔를 못하면 재계약을 하거나 방출되기도 해요.',
        sentAt: '2025-06-23T12:10:25Z',
        read: true,
    },
    {
        chatId: 'chat-19',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content:
            '아이돌이 되기 위해 가장 중요하다고 생각하는 자질은 무엇인가요?',
        sentAt: '2025-06-23T12:11:00Z',
        read: true,
    },
    {
        chatId: 'chat-20',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            "'절실함'과 '끈기'인 것 같아요. 수많은 경쟁을 뚫고 데뷔하려면 정말 간절해야 하고, 힘든 과정을 버텨낼 끈기가 필수적이에요.",
        sentAt: '2025-06-23T12:11:55Z',
        read: true,
    },
    {
        chatId: 'chat-21',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '외국어 능력도 중요한가요?',
        sentAt: '2025-06-23T12:12:20Z',
        read: true,
    },
    {
        chatId: 'chat-22',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '네, 요즘은 해외 활동이 많아서 영어, 일본어, 중국어 중 하나라도 잘하면 큰 강점이 돼요. 저도 계속 공부하고 있어요.',
        sentAt: '2025-06-23T12:13:00Z',
        read: true,
    },
    {
        chatId: 'chat-23',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '비주얼 관리는 어떻게 하세요? 피부 관리 팁이라도...',
        sentAt: '2025-06-23T12:13:30Z',
        read: true,
    },
    {
        chatId: 'chat-24',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '하하, 별건 없지만 클렌징을 정말 꼼꼼히 하고, 1일 1팩을 실천하려고 노력해요. 물 많이 마시는 것도 기본이고요.',
        sentAt: '2025-06-23T12:14:15Z',
        read: true,
    },
    {
        chatId: 'chat-25',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '정말 자세한 답변 감사드립니다! 많은 도움이 됐어요.',
        sentAt: '2025-06-23T12:14:40Z',
        read: true,
    },
    {
        chatId: 'chat-26',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content: '천만에요. 궁금한 거 있으면 언제든지 또 물어보세요!',
        sentAt: '2025-06-23T12:15:10Z',
        read: true,
    },
    {
        chatId: 'chat-27',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '마지막으로, 지금 가장 힘든 점은 무엇인가요?',
        sentAt: '2025-06-23T12:15:35Z',
        read: true,
    },
    {
        chatId: 'chat-28',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '음... 미래에 대한 불확실성이 가장 힘든 것 같아요. 열심히 하고는 있는데, 언제 데뷔할 수 있을지 알 수 없으니까요.',
        sentAt: '2025-06-23T12:16:20Z',
        read: true,
    },
    {
        chatId: 'chat-29',
        chatRoomUuid: '1',
        senderUuid: 'user-me',
        receiverUuid: '1',
        content: '꼭 꿈을 이루실 수 있을 거예요! 진심으로 응원하겠습니다.',
        sentAt: '2025-06-23T12:16:50Z',
        read: true,
    },
    {
        chatId: 'chat-30',
        chatRoomUuid: '1',
        senderUuid: '1',
        receiverUuid: 'user-me',
        content:
            '감사합니다! 그 말씀에 힘이 나네요. 님도 꼭 좋은 결과 있으시길 바랄게요!',
        sentAt: '2025-06-23T12:17:30Z',
        read: true,
    },
];
